version: '3'
services:
  ollama-container:
    image: ollama/ollama
    volumes:
      - ~/.ollama:/root/.ollama
    ports:
      - 11434:11434
  frontend-server:
    image: frontend-server
    ports:
      - 8501:8501
  miraegpt-server:
    image: miraegpt-server
    ports:
      - 8000:8000
    env_file:
      - .env