version: '3'
services:
  ollama-container:
    image: ollama/ollama
    volumes:
      - ~/.ollama:/root/.ollama
    ports:
      - 11434:11434
  miraegpt-server:
    image: miraegpt-server
    ports:
      - 8000:8000
    environment:
      - OLLAMA_URL=http://ollama-container:11434
    env_file:
      - .env
    depends_on:
      - ollama-container
  frontend-server:
    image: frontend-server
    ports:
      - 8501:8501
    environment:
      - BACKEND_URL=http://miraegpt-server:8000/gpt/invoke
    depends_on:
      - miraegpt-server
  ngrok:
    image: ngrok/ngrok
    command: 'http --domain marlin-winning-frequently.ngrok-free.app frontend-server:8501' 
    ports:
      - "4040:4040" 
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    depends_on:
      - frontend-server
    expose:
      - 4040